name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: NPM
      run: npm install
