name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: NPM
      run: npm install
      
  docker:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [npm]
    steps:
    - uses: actions/checkout@v3
    - name: Criando a Imagem
      run: docker build -t api .
